version: '3.7'
services:
  asynq-worker:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: asynq-worker
    env_file:
      - .env
    ports:
      - 9000:9000
    command: air http
    volumes:
      - ./:/app

  asynq-redis:
    container_name: asynq-redis
    image: redis:latest
    ports:
      - "6381:6379"

networks:
    default:
        name: go-skeleton-network
